#!/usr/bin/env python

# 3/7/2015
# Function that will handle storing the private key on a system.

from Crypto.Cipher import AES
from Crypto import Random

def function1(password, privateKey):
    vector = Random.new().read(AES.block_size)
    cipher = AES.new(password, AES.MODE_CFB, vector)
    message = vector + cipher.encrypt(privateKey)
    return message, vector

def main():
    encrypted, vector = function1(b'passwordpassword', b'thisisprivateee')
    cipher = AES.new(b'passwordpassword', AES.MODE_CFB, vector)
    message = (vector + cipher.decrypt(encrypted))
    # this isn't printing what I expect, will have to ask about what I'm doing wrong
    print(message)

if __name__ == "__main__":
    main()
